package com.wizzadrds.theworldremembers.memory;

public enum MemoryEventType {
    PLAYER_GAVE_BREAD,
    PLAYER_GAVE_ITEM,
    PLAYER_RECEIVED_ITEM,
    NPC_TRADED_ITEM,
    NPC_COLLECTED_ITEM,
    NPC_STORED_ITEM,
    NPC_RETRIEVED_ITEM,
    NPC_USED_ITEM,
    PLAYER_STOLE_ITEM,
    PLAYER_THREATENED_NPC,
    PLAYER_ATTACKED_NPC,
    PLAYER_SAVED_NPC,
    GOLEM_CALLED_FOR_HELP,
    GOLEM_DEFENDED_VILLAGE,
    GOLEM_KILLED,
    VILLAGE_PROPERTY_DAMAGED
}
